/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ProductWorkArea;

import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Product.Product;
import Model.Location.Location;
import Model.Organization.BillingOrganization;
import Model.Organization.EmergencyOrganization;
import Model.Organization.ProductOrganization;
import Model.Organization.Organization;
import Model.Organization.CustomerOrganization;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.BillingWorkRequest;
import Model.WorkQueue.EmergencyCustomerRequest;
import Model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felicia
 */
public class ProductRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProductRequestJPanel
     */
     JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecosystem;
    Location location;
    UserAccount userAccount;
    Organization organization;
    public ProductRequestJPanel(JPanel userProcessContainer, Location network,Enterprise enterprise,Organization organization
            ,UserAccount userAccount, EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.enterprise = enterprise;
        this.location = network;
        this.userAccount =userAccount;
        this.organization = organization;
        populateCombo();
        populateRequestTable();
    }

    public void populateRequestTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblProductReq.getModel();

        model.setRowCount(0);
         Organization Billingorg = null;
       for(Location network : ecosystem.getLocationList())
       {
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())  
            {
              for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                  if(organization instanceof BillingOrganization)
                  {
                         Billingorg = organization;
                         break;
                     }
                 }
            }
       }
       
       for(WorkRequest wr : Billingorg.getWorkQueue().getWorkRequestList())
       {
           if(wr instanceof BillingWorkRequest )
           {
               BillingWorkRequest billWrkReq = (BillingWorkRequest)wr;
                Object[] row = new Object[10];
                
                row[0] = billWrkReq;
                row[1] = billWrkReq.getSender().getEmployee().getName();
                row[2] = billWrkReq.getProductId();
                row[3] = billWrkReq.getProductName();
                row[4] = billWrkReq.getProduct().getAvailableQuant() ;
                row[5] = billWrkReq.getProduct().getCost();
                row[6] = billWrkReq.getProductPrice();
                row[7] = billWrkReq.getStatus();
                row[8] = billWrkReq.getRequestdate();
                row[9] = billWrkReq.getResolveDate();
                model.addRow(row);
           }
           
       }
           //BillingWorkRequest
    }
    
     private void populateCombo() {
        productJComboBox.removeAllItems();
        
        for(Product equipment : ecosystem.getEquipmentList().getproductList())
        {
            productJComboBox.addItem(equipment);
        }
     }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtProductCost = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtquant = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotalCost = new javax.swing.JTextField();
        btnBillingReq = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductReq = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        productJComboBox = new javax.swing.JComboBox();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("PRODUCT REQUEST PAGE");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 348, 40));

        jLabel3.setText("Product Price :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 291, -1, -1));
        add(txtProductCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 288, 179, -1));

        jLabel4.setText("Product Qunatity :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 344, -1, -1));

        txtquant.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtquantFocusLost(evt);
            }
        });
        txtquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquantActionPerformed(evt);
            }
        });
        add(txtquant, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 341, 179, -1));

        jLabel5.setText("Total Cost :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 394, -1, -1));

        txtTotalCost.setEditable(false);
        add(txtTotalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 394, 179, -1));

        btnBillingReq.setText("Request for Fund");
        btnBillingReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBillingReqActionPerformed(evt);
            }
        });
        add(btnBillingReq, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 447, 179, -1));

        tblProductReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "BillingRequestId", "Sender", "ProductId", "ProductName", "No of Units", "Product Price", "totalProductCost", "Status", "Request Date", "Resolve Date"
            }
        ));
        jScrollPane2.setViewportView(tblProductReq);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 1087, 115));

        jLabel6.setText("Select Product :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 238, -1, -1));

        productJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        productJComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productJComboBoxActionPerformed(evt);
            }
        });
        add(productJComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(464, 235, 179, -1));

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 447, 114, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ProductsBG1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 880, 770));
    }// </editor-fold>//GEN-END:initComponents

    private void productJComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productJComboBoxActionPerformed
        // TODO add your handling code here:
        Product equipment = (Product) productJComboBox.getSelectedItem();
        if (equipment != null){
          txtProductCost.setText(String.valueOf(equipment.getCost()));
          
          //Double totalcost = Integer.parseInt(txtquant.getText()) * Double.parseDouble(txtProductCost.getText());
         // txtTotalCost.setText(String.valueOf(totalcost));
          
        }
    }//GEN-LAST:event_productJComboBoxActionPerformed

    private void btnBillingReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBillingReqActionPerformed
        // TODO add your handling code here:
        Product equipment = (Product) productJComboBox.getSelectedItem();
         Organization Billingorg = null;
       for(Enterprise enterprise : location.getEnterpriseDirectory().getEnterpriseList())  
       {
         for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
             if(organization instanceof BillingOrganization)
             {
                    Billingorg = organization;
                    break;
                }
            }
       }
         
        
        BillingWorkRequest billingReq = new BillingWorkRequest();
        billingReq.setProductId(equipment.getproductID());
        billingReq.setProductName(equipment.getproductName());
        billingReq.setProduct(equipment);
        billingReq.setSender(userAccount);
        billingReq.setSenderNetwork(location);
        billingReq.setSenderOrganization(organization);
        billingReq.setRecieverNetwork(location);
        billingReq.setRecieverOrganization(Billingorg);
        billingReq.setProductPrice(Double.parseDouble(txtTotalCost.getText()));
        billingReq.setNoOfUnits(Integer.parseInt(txtquant.getText()));
        billingReq.setRequestdate(new Date());
        billingReq.setStatus("Fund Requested");
        
       
          
        
        //billingReq.setRecieverOrganization(Emeorg);
         for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
             if(organization instanceof ProductOrganization                        )
             {
                   billingReq.setSenderOrganization(organization); 
                    break;
                }
            }
        
        Billingorg.getWorkQueue().addWorkRequest(billingReq);
        //System.out.println(billingReq.getEmergencyRequestId());
        populateRequestTable();
        
        
        
    }//GEN-LAST:event_btnBillingReqActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
             userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ProductWorkAreaJPanel sysAdminwjp = (ProductWorkAreaJPanel) component;
        sysAdminwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquantActionPerformed

    private void txtquantFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtquantFocusLost
        // TODO add your handling code here:
        String qunat = txtquant.getText();
        if(!qunat.isEmpty())
        {
         Double totalcost = Integer.parseInt(txtquant.getText()) * Double.parseDouble(txtProductCost.getText());
         txtTotalCost.setText(String.valueOf(totalcost));
        }
    }//GEN-LAST:event_txtquantFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBillingReq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox productJComboBox;
    private javax.swing.JTable tblProductReq;
    private javax.swing.JTextField txtProductCost;
    private javax.swing.JTextField txtTotalCost;
    private javax.swing.JTextField txtquant;
    // End of variables declaration//GEN-END:variables
}
