/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerAgentWorkArea;



import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.RetailEmployment.Agent;
import Model.RetailEmployment.Customer;
import Model.Location.Location;
import Model.Organization.AgentOrganization;
import Model.Organization.Organization;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.AgentCheckWorkRequest;
import Model.WorkQueue.WorkRequest;


import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ajin
 */
public class CustomerAgentWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerAgentWorkAreaJPanel
     */
     JPanel userProcessContainer;
    UserAccount account;
    Organization organization;
    Enterprise enterprise;

    Location location;

    EcoSystem business;
        String value = "\\d+";
   
    public CustomerAgentWorkAreaJPanel(JPanel userProcessContainer, 

            UserAccount account,Organization organization,Enterprise enterprise,Location location,

            EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
         this.account = account;
         this.organization = organization;
         this.enterprise = enterprise;

         this.location = location;

         this.business = business;
         populateTable();
    }

    public void populateTable()
    {

        DefaultTableModel model = (DefaultTableModel) tblAgentReq.getModel();

        model.setRowCount(0);
        System.out.println("Total workreq "+account.getWorkQueue().getWorkRequestList().size());
        
        for (WorkRequest wr : account.getWorkQueue().getWorkRequestList()) {


            if(wr instanceof AgentCheckWorkRequest) {
                
                AgentCheckWorkRequest epr = (AgentCheckWorkRequest)wr;
                
                Object[] row = new Object[4];
                row[0] = epr;
                row[1] = epr.getCustomer().getCustomerName();

                row[2] = epr.getStatus();               
                row[3] = epr.getMessage();
             
                model.addRow(row);
            }
            
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();


        tblAgentReq = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtpackageLost = new javax.swing.JTextField();
        txtpackagedamage = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtrefundInitiate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtproductDamage = new javax.swing.JTextField();

        btnrequest = new javax.swing.JButton();
        btnsubmit = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());


        tblAgentReq.setModel(new javax.swing.table.DefaultTableModel(

            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request ID", "Customer", "Status", "Message"
            }
        ));

        jScrollPane1.setViewportView(tblAgentReq);


        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 642, 121));

        jLabel1.setText("Package Damaged:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 273, -1, -1));

        jLabel2.setText("Product Damaged :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));



        txtpackageLost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpackageLostActionPerformed(evt);
            }
        });
        add(txtpackageLost, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 268, 128, -1));
        add(txtpackagedamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 312, 128, -1));

        jLabel3.setText("Lost Status :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));
        add(txtrefundInitiate, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 268, 128, -1));



        jLabel4.setText("Issue with Refund.?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 310, -1, -1));


        txtproductDamage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductDamageActionPerformed(evt);
            }
        });
        add(txtproductDamage, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 312, 128, -1));


        btnrequest.setText("Request for Lab Test");
        btnrequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrequestActionPerformed(evt);
            }
        });
        add(btnrequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 398, 0, 10));

        btnsubmit.setText("Submit");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });
        add(btnsubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 385, 173, -1));

        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 96, -1));

        jButton1.setText("Raise Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 385, 173, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CUSTOMER AGENT WORK AREA");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 480, 36));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AEDTicket.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 720, 540));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:

         int selectedRow = tblAgentReq.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }

//        String compare = (String) tblAgentReq.getValueAt(selectedRow, 3);

//        if (compare.equalsIgnoreCase("completed")) {
//            JOptionPane.showMessageDialog(this, "It has been already completed!", "Warning", JOptionPane.WARNING_MESSAGE);
//            return;
//        }

//        if (txtpackageLost.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Enter an appropriate Respiratory Rate");
//            return;
//        } else if (!txtpackageLost.getText().matches(value)) {
//            JOptionPane.showMessageDialog(null, "Enter an appropriate Respiratory Rate");
//            return;
//        }
//        if (txtpackagedamage.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Enter an appropriate Blood Pressure");
//            return;
//        } else if (!txtpackagedamage.getText().matches(value)) {
//            JOptionPane.showMessageDialog(null, "Enter an appropriate Blood Pressure");
//            return;
//        }
//        if (txtproductDamage.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Enter an appropriate Heart Rate");
//            return;
//        } else if (!txtproductDamage.getText().matches(value)) {
//            JOptionPane.showMessageDialog(null, "Enter an appropriate Heart Rate");
//            return;
//        }
//        if (txtrefundInitiate.getText().trim().isEmpty()) {
//            JOptionPane.showMessageDialog(null, "Enter an appropriate Weight");
//            return;
//        } else if (!txtrefundInitiate.getText().matches(value)) {
//            JOptionPane.showMessageDialog(null, "Enter an appropriate Weight");
//            return;
//        }
//          
       // String result=txtTestResult.getText();
       //  JOptionPane.showMessageDialog(null,"Donor details added1");
       
       
        String rr = txtpackageLost.getText();
        String bp = txtpackagedamage.getText();
        String weight =txtrefundInitiate.getText();
        String hr = txtproductDamage.getText();
        AgentCheckWorkRequest cur = (AgentCheckWorkRequest) tblAgentReq.getValueAt(selectedRow, 0);
        
        cur.getCheckUp().setPackageDamage(rr);
        cur.getCheckUp().setProductDamage(bp);
        cur.getCheckUp().setHRefund(hr);
        cur.getCheckUp().setLostPackage(weight);
        cur.getCheckUp().setDate(new Date());
        cur.setResolveDate(new Date());
        cur.setStatus("Completed"); 
        
        JOptionPane.showMessageDialog(null, "Ticket Resolved");


        btnrequest.setEnabled(true);
        btnsubmit.setEnabled(false);
        populateTable();
    }//GEN-LAST:event_btnsubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

         int selectedRow = tblAgentReq.getSelectedRow();

        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }



        AgentCheckWorkRequest dcwr = (AgentCheckWorkRequest) tblAgentReq.getValueAt(selectedRow, 0);
        
        Customer customer = dcwr.getCustomer();
        Agent agent = dcwr.getAgent() ;
//        
 
   
        TicketJPanel manageNetworkJPanel = new TicketJPanel(userProcessContainer,account,enterprise,
                organization,business,location,customer,agent);

        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    private void txtproductDamageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductDamageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductDamageActionPerformed


    private void btnrequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrequestActionPerformed
        // TODO add your handling code here:


        int selectedRow = tblAgentReq.getSelectedRow();

        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }


        AgentCheckWorkRequest dcwr = (AgentCheckWorkRequest) tblAgentReq.getValueAt(selectedRow, 0);


        Customer customer = dcwr.getCustomer();
        Agent agent = dcwr.getAgent() ;
        

        RequestQueryTestJPanel manageNetworkJPanel = new RequestQueryTestJPanel(userProcessContainer,account,enterprise,
            customer,agent,organization,location,business);


        userProcessContainer.add("manageNetworkJPanel", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnrequestActionPerformed

    private void txtpackageLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpackageLostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpackageLostActionPerformed


    private void txtpackageLostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpackageLostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpackageLostActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnrequest;
    private javax.swing.JButton btnsubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JTable tblAgentReq;
    private javax.swing.JTextField txtpackageLost;
    private javax.swing.JTextField txtpackagedamage;
    private javax.swing.JTextField txtproductDamage;
    private javax.swing.JTextField txtrefundInitiate;

    // End of variables declaration//GEN-END:variables
}
