/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerAgentWorkArea;

import Model.EcoSystem;
import Model.Employee.Employee;
import Model.Enterprise.Enterprise;
import Model.RetailEmployment.Agent;
import Model.RetailEmployment.Customer;
import Model.Location.Location;
//import Business.Mail.Mail;
import Model.Organization.DepartmentOrganization;
import Model.Organization.Organization;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.LabTestWorkRequest;
import Model.WorkQueue.DeoartmentWorkRequest;
import Model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
////import javax.mail.MessagingException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ajin
 */
public class RequestQueryTestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestQueryTestJPanel
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Customer customer;
    private EcoSystem ecosystem;
    Organization organization;
    Agent agent;
    Location network;
    
    public RequestQueryTestJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, Customer customer,
            Agent agent, Organization organization,Location network, EcoSystem business) {
        initComponents();
         this.ecosystem = business;
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.customer = customer;
        this.agent = agent;
        this.organization = organization;
        this.network = network;
        
        populateTable();

        //valueLabel.setText(enterprise.getName());
        lblAgentName.setText(agent.getAgentName());
        lblCustomerName.setText(customer.getCustomerName());
    }
    
     public void populateTable()
    {
        
         DefaultTableModel model = (DefaultTableModel) tblLabRequest.getModel();
        model.setRowCount(0);
        
         Organization org = null;
       for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())  
       {
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof DepartmentOrganization) {
                    System.out.println(organization.getType());
                    org = organization;
                    break;
                }
            }
       }
        if (org != null) {
            for(WorkRequest wr : org.getWorkQueue().getWorkRequestList())
            {
                if(wr instanceof DeoartmentWorkRequest)
                {
                    DeoartmentWorkRequest lwr = (DeoartmentWorkRequest)wr;
                    if(lwr.getCustomer().equals(customer))
                    {
                        Object[] row = new Object[6];
                        row[0] = lwr.getDepartmentRequestId();
                        row[1] = lwr.getCustomer().getCustomerName();
                        row[2] = lwr.getSpecialType();               
                        row[3] = lwr.getLDepartmentTestName();
                        row[4] = lwr.getDepartmentAdminFeedback();
                        row[5] = lwr.getRequestdate();

                        model.addRow(row);
                    }
                    
                }
            }
            //userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLabRequest = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblAgentName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSpecialType = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDepartmentTestName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtMessage = new javax.swing.JTextField();
        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLabRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Request ID", "Customer", "Special Type", "Department  Name", "Feedback", "Request Date"
            }
        ));
        jScrollPane1.setViewportView(tblLabRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 88, 663, 129));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("REQUEST PAGE");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, 28));

        jLabel1.setText("Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 247, -1, -1));

        lblCustomerName.setText("<Name>");
        add(lblCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 247, 135, -1));

        jLabel2.setText("Agent Name: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 247, -1, -1));

        lblAgentName.setText("<Name>");
        add(lblAgentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 247, 135, -1));

        jLabel3.setText("Special Type :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 296, -1, -1));
        add(txtSpecialType, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 291, 189, -1));

        jLabel5.setText("Department Name :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 352, -1, -1));
        add(txtDepartmentTestName, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 347, 189, -1));

        jLabel4.setText("Message :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 408, -1, -1));
        add(txtMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 403, 189, -1));

        requestTestJButton.setText("Request");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 459, 175, -1));

        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 459, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed

        String message = txtMessage.getText();
        String DepartmentTestName = txtDepartmentTestName.getText();
        String Sepcial = txtSpecialType.getText();
       

        DeoartmentWorkRequest request = new DeoartmentWorkRequest();
        request.setMessage(message);
        request.setSender(userAccount);
        request.setDepartmentName(DepartmentTestName);
        request.setSpecialType(Sepcial);
        request.setStatus("Requested");
        request.setCustomer(customer);
        request.setAgent(agent);
        request.setRequestdate(new Date());
        System.out.println(customer.getCustomerName());
        //   customer.getPdr().addRequest(request);

        Organization org = null;
       for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())  
       {
            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (organization instanceof DepartmentOrganization) {
                    org = organization;
                    break;
                }
            }
       }
        if (org != null) {
            org.getWorkQueue().getWorkRequestList().add(request);
            //userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        JOptionPane.showMessageDialog(null, "Request message sent");
        populateTable();
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CustomerAgentWorkAreaJPanel dwjp = (CustomerAgentWorkAreaJPanel) component;

      
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAgentName;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTable tblLabRequest;
    private javax.swing.JTextField txtDepartmentTestName;
    private javax.swing.JTextField txtMessage;
    private javax.swing.JTextField txtSpecialType;
    // End of variables declaration//GEN-END:variables
}
