/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerAgentWorkArea;

import Model.HumanResource.TicketList;
import Model.HumanResource.TicketListDir;
import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.Product.ProductList;
import Model.RetailEmployment.Agent;
import Model.RetailEmployment.Customer;
import Model.HumanResource.HumanR;
import Model.Location.Location;
import Model.Organization.AgentOrganization;
import Model.Organization.HumanResourceOrganization;
import Model.Organization.Organization;
/////import Business.Organization.PharmacyOrganization;
import Model.UserAccount.UserAccount;
import Model.WorkQueue.AgentWorkRequest;
import Model.WorkQueue.WorkRequest;

import java.awt.CardLayout;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Date;
import java.util.Properties;
import java.util.logging.Level;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
/**
 *
 * @author ajin
 */
public class TicketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TicketJPanel
     */
      private Organization organization;
    private Enterprise enterprise;

    private UserAccount userAccount;
    private JPanel userProcessContainer;

    //private TicketList prescription;
    private AgentWorkRequest agentreq;
    private Location location;
    private EcoSystem system;
    private static Logger log = Logger.getLogger(TicketJPanel.class);
    private static final String CLASS_NAME = TicketJPanel.class.getName();
    private static final String filePath = "./ticket data.txt";
    private Customer customer;
    private Agent agent;
    public TicketJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, 
            Organization organization, 
            EcoSystem system, Location network,Customer customer,Agent agent) {
        initComponents();
         this.agent = agent;

        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.organization = organization;

        this.location = network;
        this.system = system;
        this.customer = customer;

        
        //populateWorkRequestTable();
        DateChooser.setMinSelectableDate(new Date());
        populatefields();

    }
    
    public void populatefields()
    {

        txtName.setText(customer.getCustomerName());
        txtAge.setText(String.valueOf(customer.getAge()));
        txtGender.setText(customer.getGender());

    }
    
    
    
    
        
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        cbType = new javax.swing.JComboBox<>();

        jLabel6 = new javax.swing.JLabel();
        noofTimesTxt = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        noofDaysTxt = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();

        ticketJTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();


        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("CUSTOMER AGENT TICKET PAGE");

        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 17, 510, 40));


        jLabel2.setText("Name :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 90, -1, -1));

        txtName.setEditable(false);
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 85, 167, -1));

        jLabel3.setText("Age:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 146, -1, -1));

        txtAge.setEditable(false);
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 141, 167, -1));

        jLabel4.setText("Gender");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 202, -1, -1));

        txtGender.setEditable(false);
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 197, 167, -1));

        jLabel5.setText("Type:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));


        cbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Edible", "Cosmetics", "Deli", "Toileteries", "None" }));
        cbType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeActionPerformed(evt);
            }
        });
        add(cbType, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 253, 167, -1));


        jLabel6.setText("Qty of Product:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 315, -1, -1));
        add(noofTimesTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 310, 167, -1));

        jLabel7.setText("Days to Exp:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, -1, -1));
        add(noofDaysTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 366, 167, -1));

        jButton1.setText("Add to Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 267, -1));

        jLabel8.setText("Date: ");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 422, -1, -1));
        add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 422, 167, -1));


        ticketJTable.setModel(new javax.swing.table.DefaultTableModel(

            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Type", "Qty of Product", "Days to Exp"
            }
        ));

        jScrollPane1.setViewportView(ticketJTable);


        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 557, 560, 139));

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 190, -1));

        jButton2.setText("Send Ticket To Customer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 230, -1));


        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/AEDTicket.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 860));

    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);

        log.debug("going back to Agent work area");

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

         TicketList p = new TicketList();
       // p.setProblem(diagnosisComboBox.getSelectedItem().toString());
        p.setTypeName(cbType.getSelectedItem().toString());
        p.setNoofTimesInaday((Integer) noofTimesTxt.getValue());
        p.setTotalDays((Integer) noofDaysTxt.getValue());
        p.setNetworkName(location.getName());

        
        
        
//        String age = ageTxtField.getText();
        boolean flag = true;
        try {
           // Integer.parseInt(age);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Age must be integer!");
            flag = false;
            return;
        }


         if(((Integer) noofTimesTxt.getValue())==0|| ((Integer) noofDaysTxt.getValue())==0)
                {
                     JOptionPane.showMessageDialog(null, "Please enter the details !");

             flag = false;
             return;
                }
         if(DateChooser.getDate()==null)
         {
             JOptionPane.showMessageDialog(null, "Please select the date !");
             flag = false;
             return;
         }

         System.out.println("cbType.getSelectedIndex() "+  cbType.getSelectedIndex());
         
//      

        
        if (flag == true) {
            
            

            customer.getTicketlist().addTicket(p);

//            
            
           

            populateWorkRequestTable();

            saveRecord(p.getNetworkName(),p.getProblem(),p.getTypeName(),p.getNoofTimesInaday(),p.getTotalDays());
           
             noofTimesTxt.setValue(0);
             noofDaysTxt.setValue(0);
          
             cbType.setSelectedIndex(0);

            
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    public void populateWorkRequestTable() {

        DefaultTableModel model = (DefaultTableModel) ticketJTable.getModel();

        model.setRowCount(0);

        for (TicketList prescription : customer.getTicketlist().getPrescriptionList()) {
           
                Object[] row = new Object[5];
                row[0] = prescription.getTypeName();

                row[1] = prescription.getNoofTimesInaday();
                row[2] = prescription.getTotalDays();         
                model.addRow(row);
        }

    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        

        log.info("Send to Customer");
        String prescrip ="";
        for (TicketList prescription : customer.getTicketlist().getPrescriptionList()) {
           
               
               
               prescrip += ", Quantity of Product : " + prescription.getNoofTimesInaday();
              prescrip  += ", Number of Days to Expiry" + prescription.getTotalDays();         
            
        }
        
        SendEmail(customer.getEmailAddress(),prescrip);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTypeActionPerformed


    public void saveRecord(String network,String disease,String medicine,int times, int days){
        try {
            FileWriter file = new FileWriter(filePath,true);
            BufferedWriter bw = new BufferedWriter(file);
            PrintWriter pw = new PrintWriter(bw);

            pw.println("Product Type - " + medicine+", Qty of Product "+times + ", Expiry Days Left"+days);
            pw.flush();
            pw.close();
            log.debug("saving ticket details to ticket data.txt");
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(TicketJPanel.class.getName()).log(Level.SEVERE, null, ex);
            log.error("ticket data.txt" +ex);

        }
        
    }
    
    public void SendEmail(String emailAddress, String Prescription)
    {
        System.out.println("Inside Email ");
         String to = emailAddress;

        String from = "siddajinfel@gmail.com";
        String pass = "qaclgfzmxomfdkde";

// Assuming you are sending email from localhost
// String host = "192.168.0.16";

// Get system properties
        Properties properties = System.getProperties();
        String host = "smtp.gmail.com";

        properties.put("mail.smtp.starttls.enable", "true");

        properties.put("mail.smtp.ssl.trust", host);
        properties.put("mail.smtp.user", from);
// properties.put("mail.smtp.password", pass);
        properties.put("mail.smtp.port", "587");
        properties.put("mail.smtp.auth", "true");

// Setup mail server
// properties.setProperty("mail.smtp.host", host);
// properties.put("mail.smtp.starttls.enable", "true");
// Get the default Session object.
        Session session = Session.getDefaultInstance(properties);

        try {
// Create a default MimeMessage object.
            MimeMessage message = new MimeMessage(session);

// Set From: header field of the header.
            message.setFrom(new InternetAddress(from));

// Set To: header field of the header.
            message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
            String htmlText = ("<div style=\"color:red;\">BRIDGEYE</div>");
            message.setContent(htmlText, "text/html");

// Set Subject: header field

            message.setSubject("Customer Query Registration");
            
            
            String msg = "Ticket generated by your Agent - ";

            msg += Prescription;
                    
// String text= "<table><tr><td>EmpId</td><td>Emp name</td><td>age</td></tr><tr><td>value</td><td>value</td><td>value</td></tr></table>";
            message.setText(msg);
// Send message
            Transport transport = session.getTransport("smtp");
            transport.connect(host, from, pass);
            transport.sendMessage(message, message.getAllRecipients());
            transport.close();

                JOptionPane.showMessageDialog(null,"Ticket has been successfully sent....");

            System.out.println("Sent message successfully....");
        } catch (MessagingException mex) {
            mex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Invalid email id");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JButton btnBack;

    private javax.swing.JComboBox<String> cbType;

    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;

    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner noofDaysTxt;
    private javax.swing.JSpinner noofTimesTxt;
    private javax.swing.JTable ticketJTable;

    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
