/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HumanResourceUnitArea;


import Model.EcoSystem;
import Model.Enterprise.Enterprise;
import Model.HumanResource.HumanR;
import Model.HumanResource.HREmpList;
import Model.Location.Location;
import Model.Organization.BillingOrganization;
import Model.Organization.HumanResourceOrganization;
import Model.Organization.Organization;

import Model.UserAccount.UserAccount;


import Model.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.apache.log4j.Logger;
/**
 *
 * @author felicia
 */
public class PayrollWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form PayrollWorkArea
     */
    JPanel userProcessContainer;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;

    private Organization org;
    private HumanResourceOrganization payrolorg;
    private Location location;
    private static Logger log = Logger.getLogger(PayrollWorkArea2.class);
    private static final String CLASS_NAME = PayrollWorkArea2.class.getName();

    public PayrollWorkArea(JPanel userProcessContainer, UserAccount userAccount, Organization organization, Enterprise enterprise, 
            Location location,EcoSystem ecoSystem) {
        initComponents();
         this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
//        this.payrolorg = organization;
        this.location = location;
        this.ecoSystem = ecoSystem;
        
//        populateDocTable();
        log.debug(userAccount+" "+"logged in");
         Organization medicineOrg = null;
      
            for(Enterprise enrise : location.getEnterpriseDirectory().getEnterpriseList())  
            {
              for (Organization org : enrise.getOrganizationDirectory().getOrganizationList()) {
                  if(org instanceof HumanResourceOrganization)
                  {
                         this.payrolorg = (HumanResourceOrganization) org;
                        
                         break;
                     }
                 }
            }
       reorderTable();
    }

    public void reorderTable() {
        int rowCount = reorderTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel) reorderTable.getModel();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
        for (HumanR mi : payrolorg.getHRList()) {
            Object row[] = new Object[4];
            row[0] = mi;
            row[1] = mi.getSerialNumber();
            row[2] = mi.getAvailQuantity();
            row[3] = mi.getReorderStatus();
           // row[4] = 
            //row[5] = mi.getReorderStatus();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reorderTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        serialNumberTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        departmentNameTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        availQuantityTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnAddDepartment = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("PAYROLL WORK AREA");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 257, 38));

        reorderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Employee Name", "Employee ID", "Available Icentive", "Status"
            }
        ));
        jScrollPane1.setViewportView(reorderTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 109, 794, 140));

        jLabel2.setText("Employee ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));
        add(serialNumberTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 279, 250, 30));

        jLabel3.setText("Employee Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 346, -1, -1));
        add(departmentNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 339, 250, 30));

        jLabel4.setText("Available Icentive: ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, 14));
        add(availQuantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 399, 250, 30));

        jLabel5.setText("Status :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 465, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Available", "Not Available" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 459, 250, 30));

        btnAddDepartment.setText("Add ");
        btnAddDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDepartmentActionPerformed(evt);
            }
        });
        add(btnAddDepartment, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 507, 250, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDepartmentActionPerformed
        // TODO add your handling code here:
        
         HumanR m = new HumanR();
        String name = departmentNameTxtField.getText().trim();
        String error_message = "";
        String avail = availQuantityTxtField.getText();
        try {
            Integer.parseInt(avail);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Available quantity must be integer");
            return;

        }
        if(name.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please enter the name ");
            return;
        }
        
        m.setHRName(departmentNameTxtField.getText());
        try{
        int availableQuantity = Integer.parseInt(availQuantityTxtField.getText());
        m.setAvailQuantity(availableQuantity);
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "serial number must be integer!");
            return;
        }
        try{
        int serialNumber = Integer.parseInt(serialNumberTxtField.getText());
        m.setSerialNumber(serialNumber);
        }
        catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "serial number must be integer!");
            return;
        }
        //String req = reqQuantityTxtField.getText();
        try {
           
           // m.setRequiredQuantity( Integer.parseInt(req));
        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(null, "Required quantity must be integer!");
            return;
        }
       
//        ArrayList<String> medicineCheck = new ArrayList<>();
//        for(MedicalInventory mc:payrolorg.getHRList())
//        {
//            medicineCheck.add(mc.getHRName().toLowerCase());
//        }
//        if(medicineCheck.contains(name.toLowerCase()))
//        {
//            JOptionPane.showMessageDialog(null, "medicine already existed please update the quantity by clicking on view details");
//            return;
//        }
    String status =  jComboBox1.getSelectedItem().toString();
    System.out.println(status);
        m.setReorderStatus(status);
        payrolorg.addDepartment(m);
       
        
        

        DefaultTableModel dtm = (DefaultTableModel) reorderTable.getModel();

        dtm.setRowCount(0);
        for (HumanR mi : payrolorg.getHRList()) {
            Object row[] = new Object[4];
            row[0] = mi;
            row[1] = mi.getSerialNumber();
            row[2] = mi.getAvailQuantity();
            row[3] =  mi.getReorderStatus();
          
            dtm.addRow(row);
        }

        JOptionPane.showMessageDialog(null, "Department Added Successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
        log.debug("department added successfully");
        serialNumberTxtField.setText("");
        departmentNameTxtField.setText("");
        availQuantityTxtField.setText("");
        //reqQuantityTxtField.setText("");
        
    }//GEN-LAST:event_btnAddDepartmentActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField availQuantityTxtField;
    private javax.swing.JButton btnAddDepartment;
    private javax.swing.JTextField departmentNameTxtField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reorderTable;
    private javax.swing.JTextField serialNumberTxtField;
    // End of variables declaration//GEN-END:variables
}
